In [69]:
import numpy as np
import pandas as pd
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.models import load_model
from keras.utils import to_categorical
import pandas as pd

In [5]:
#convert to pandas
#df = pd.read_csv('ann-train.csv')

In [8]:
dataset = np.loadtxt("ann-train.csv", delimiter=",")

In [13]:
X = dataset[:,0:21]
Y = dataset[:,21]

In [17]:
encoded = to_categorical(Y)

In [25]:
encoded[23:48]

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.]])

In [26]:
#delete first row
encoded_a = np.delete(encoded,0,1)

In [28]:
encoded_a[23:48]

array([[ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.]])

In [30]:
#create neural network
model = Sequential()
model.add(Dense(50, input_dim=21, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(3, activation='sigmoid'))

In [31]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [32]:
model.fit(X, encoded_a, epochs=200, batch_size=20)

Epoch 1/200
3772/3772 [==============================] - 5s 1ms/step - loss: 0.4725 - acc: 0.8982
Epoch 2/200
3772/3772 [==============================] - 2s 438us/step - loss: 0.2890 - acc: 0.9247
Epoch 3/200
3772/3772 [==============================] - 2s 430us/step - loss: 0.2731 - acc: 0.9247
Epoch 4/200
3772/3772 [==============================] - 2s 414us/step - loss: 0.2555 - acc: 0.9250
Epoch 5/200
3772/3772 [==============================] - 2s 437us/step - loss: 0.2306 - acc: 0.9290
Epoch 6/200
3772/3772 [==============================] - 2s 437us/step - loss: 0.2087 - acc: 0.9369
Epoch 7/200
3772/3772 [==============================] - 2s 428us/step - loss: 0.1945 - acc: 0.9411
Epoch 8/200
3772/3772 [==============================] - 2s 410us/step - loss: 0.1868 - acc: 0.9454
Epoch 9/200
3772/3772 [==============================] - 1s 397us/step - loss: 0.1805 - acc: 0.9449
Epoch 10/200
3772/3772 [==============================] - 1s 386us/step - loss: 0.1786 - acc: 0.9451
E

3772/3772 [==============================] - 1s 359us/step - loss: 0.0220 - acc: 0.9899
Epoch 163/200
3772/3772 [==============================] - 1s 345us/step - loss: 0.0247 - acc: 0.9894
Epoch 164/200
3772/3772 [==============================] - 1s 358us/step - loss: 0.0215 - acc: 0.9899
Epoch 165/200
3772/3772 [==============================] - 1s 384us/step - loss: 0.0211 - acc: 0.9913
Epoch 166/200
3772/3772 [==============================] - 2s 423us/step - loss: 0.0219 - acc: 0.9905
Epoch 167/200
3772/3772 [==============================] - 1s 394us/step - loss: 0.0219 - acc: 0.9894
Epoch 168/200
3772/3772 [==============================] - 1s 381us/step - loss: 0.0210 - acc: 0.9905
Epoch 169/200
3772/3772 [==============================] - 2s 406us/step - loss: 0.0187 - acc: 0.9931
Epoch 170/200
3772/3772 [==============================] - 1s 397us/step - loss: 0.0189 - acc: 0.9920
Epoch 171/200
3772/3772 [==============================] - 1s 391us/step - loss: 0.0238 - acc: 0

In [ ]:
mode.save_model('ty.h5')

In [10]:
model = load_model('ty.h5')

In [13]:
#test model
dataset_test = np.loadtxt("ann-test.csv", delimiter=",")

In [14]:
X_test = dataset_test[:,0:21]
Y_test = dataset_test[:,21]

In [17]:
encoded_test = to_categorical(Y_test)

In [18]:
encoded_a_test = np.delete(encoded_test,0,1)

In [20]:
model.evaluate(X_test,encoded_a_test, batch_size=30)

3428/3428 [==============================] - 1s 249us/step


[0.097482582293506065, 0.97753791206776053]

In [22]:
#here and below, is just getting prediction output to csv for further analysis
prediction = model.predict(X_test)

In [25]:
prediction[:20]

array([[  1.44062529e-09,   2.05833721e-03,   5.43361902e-02],
       [  2.46328565e-13,   1.99364740e-06,   9.97786045e-01],
       [  1.36582123e-38,   2.99131142e-09,   9.99949932e-01],
       [  3.34386772e-12,   1.78007645e-06,   9.98532772e-01],
       [  2.36581927e-18,   1.95397979e-06,   9.97506797e-01],
       [  6.74325386e-15,   4.89793365e-06,   9.94984746e-01],
       [  5.18812709e-17,   1.18698881e-06,   9.79025543e-01],
       [  1.11711217e-10,   5.00440649e-07,   9.96130109e-01],
       [  9.44382232e-16,   7.52121252e-07,   9.99547541e-01],
       [  2.62235129e-11,   2.61347795e-05,   9.49760854e-01],
       [  7.25720346e-01,   8.06799217e-05,   1.18343735e-06],
       [  2.15526532e-30,   2.67389979e-18,   1.00000000e+00],
       [  2.16690947e-19,   1.74458506e-07,   9.97863591e-01],
       [  2.36032682e-09,   5.86498427e-05,   4.83931936e-02],
       [  8.12812744e-20,   2.49675886e-05,   7.92455375e-01],
       [  7.16397901e-17,   1.34512925e-06,   9.9400490

In [28]:
encoded_a_test[:20]

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.]])

In [52]:
ipred = []
iv_pred = []
for i in range(len(encoded_a_test)):
    ipred = np.argmax(encoded_a_test[i])
    ipred = ipred + 1
    iv_pred.append(str(ipred))

In [67]:
iv_pred

['2',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '1',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '2',
 '3',
 '3',
 '3',
 '2',
 '2',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '2',
 '3',
 '2',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '1',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '1',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '1',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '2',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '2',
 '1',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '2',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '2',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '2'

In [65]:
Y_test_list = Y_test.tolist()

In [66]:
Y_test_list

[2.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 1.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 2.0,
 3.0,
 3.0,
 3.0,
 2.0,
 2.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 2.0,
 3.0,
 2.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 1.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 1.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 1.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 2.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 2.0,
 1.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 2.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 2.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 2.0

In [70]:
df = pd.DataFrame(iv_pred)
df.to_csv('iv_pred.csv', index=False)